name: "Create Github release"
description: "Create Github release"
inputs:
  go_os:
    required: true
    description: Define the OS to compile binary for - https://pkg.go.dev/internal/goos
  go_arch:
    required: true
    description: Define the architecture to compile binary for - https://pkg.go.dev/internal/goarch
  osctrl_component:
    required: true
    description: Define the osctrl component to compile
  commit_tag:
    required: true
    description: Define the git commit tagged version

runs:
  using: "composite"
  steps:
    ########################### Checkout code ###########################
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    ########################### Download osctrl binary ###########################
    - name: Download osctrl binaries
      uses: actions/download-artifact@v3
      with:
        name: osctrl-${{ inputs.osctrl_component }}-${{ inputs.commit_tag }}-${{ inputs.go_os }}-${{ inputs.go_arch }}.bin

    ########################### Download osctrl DEB packages ###########################
    - name: Download osctrl DEB package
      uses: actions/download-artifact@v3
      with:
        name: osctrl-${{ inputs.osctrl_component }}_${{ inputs.commit_tag }}_${{ inputs.go_arch }}.deb


    ########################### Create release ###########################
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          osctrl-*.deb
          osctrl-*.bin
        body_path: ./CHANGELOG.md
