version: "3"

services:
  osctrl-db:
    container_name: osctrl-db
    image: postgres:10-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: osctrl
      POSTGRES_PASSWORD: osctrl
      POSTGRES_DB: osctrl
    ports:
      - "5432:5432"
    networks:
      - private-net
  osctrl-tls:
    container_name: osctrl-tls
    depends_on:
      - "osctrl-db"
    build:
      context: .
      dockerfile: "deploy/docker/tls/Dockerfile"
    links:
      - "osctrl-db"
    ports:
      - "9000:9000"
    networks:
      - private-net
    volumes:
      - ./deploy/docker/config:/osctrl-tls/config
  osctrl-admin:
    container_name: osctrl-admin
    depends_on:
      - "osctrl-db"
    build:
      context: .
      dockerfile: "deploy/docker/admin/Dockerfile"
    links:
      - "osctrl-db"
    ports:
      - "9001:9001"
    networks:
      - private-net
    volumes:
      - ./deploy/docker/certs:/osctrl-admin/certs
      - ./deploy/docker/config:/osctrl-admin/config
  osctrl-api:
    container_name: osctrl-api
    depends_on:
      - "osctrl-db"
    build:
      context: .
      dockerfile: "deploy/docker/api/Dockerfile"
    links:
      - "osctrl-db"
    ports:
      - "9002:9002"
    networks:
      - private-net
    volumes:
      - ./deploy/docker/config:/osctrl-api/config
  osctrl-nginx:
    image: "nginx:1.13.5"
    container_name: osctrl-nginx
    depends_on:
      - "osctrl-tls"
      - "osctrl-admin"
      - "osctrl-api"
    ports:
      - "443:443"
      - "8443:8443"
    expose:
      - "443"
      - "8443"
    networks:
      - public-net
      - private-net
    volumes:
      - ./deploy/docker/certs:/etc/certs
      - ./deploy/docker/config:/etc/nginx/conf.d
  osquery-ubuntu20:
    container_name: osquery-ubuntu20
    depends_on:
      - "osctrl-admin"
      - "osctrl-nginx"
    build:
      context: .
      dockerfile: "deploy/docker/nodes/ubuntu20/Dockerfile"
    links:
      - "osctrl-nginx"
    networks:
      - public-net
    volumes:
      - ./deploy/docker/config:/config
      - ./deploy/docker/certs:/certs
  # osquery-ubuntu18:
  #  container_name: osquery-ubuntu18
  #  depends_on:
  #    - "osctrl-admin"
  #    - "osctrl-nginx"
  #  build:
  #    context: .
  #    dockerfile: "deploy/docker/nodes/ubuntu18/Dockerfile"
  #  links:
  #    - "osctrl-nginx"
  #  networks:
  #    - public-net
  #  volumes:
  #    - ./deploy/docker/config:/config
  #    - ./deploy/docker/certs:/certs
  # osquery-debian9:
  #   container_name: osquery-debian9
  #   depends_on:
  #     - "osctrl-nginx"
  #   build:
  #     context: .
  #     dockerfile: "deploy/docker/nodes/debian9/Dockerfile"
  #   links:
  #     - "osctrl-nginx"
  #   networks:
  #     - public-net
  #   volumes:
  #     - ./deploy/docker/config:/config
  #     - ./deploy/docker/certs:/certs
  # osquery-centos7:
  #   container_name: osquery-centos7
  #   depends_on:
  #     - "osctrl-nginx"
  #   build:
  #     context: .
  #     dockerfile: "deploy/docker/nodes/centos7/Dockerfile"
  #   links:
  #     - "osctrl-nginx"
  #   networks:
  #     - public-net
  #   volumes:
  #     - ./deploy/docker/config:/config
  #     - ./deploy/docker/certs:/certs

volumes:
  db-data:

networks:
  public-net:
  private-net:
