name: Build OSctrl binaries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        components: ['tls', 'admin', 'api', 'cli']
        goos: ['linux']
        goarch: ['amd64']
    steps:
      ######################################## Checkout code ########################################
      - name: Checkout code
        uses: actions/checkout@v2

      ######################################## Install go to env ########################################
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go version

      ######################################## Get GO deps ########################################
      - name: Get GO deps
        run: go mod download

      ######################################## Build osctrl component ########################################
      - name: Build osctrl-tls
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./bin/osctrl-${{ matrix.components }}-${{ matrix.goos }}-${{ matrix.goarch }}.bin ./${{ matrix.components }}

      ######################################## Create ZIP of build artifacts ########################################
      # https://newbedev.com/getting-current-branch-and-commit-hash-in-github-action
      - name: Create ZIP of build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: osctrl-binaries-${GITHUB_SHA::8}.zip
          path: bin
