on:
  create:
    tags:
      - 'v*'

name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04
    strategy:
      matrix: 
        components: ['tls', 'admin', 'api', 'cli']
        #goos: ['linux']
        #goarch: ['amd64']
    steps:
      ######################################## Checkout code ########################################
      - name: Checkout code
        uses: actions/checkout@v2

      ######################################## Create release ########################################
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md

      ######################################## Add build artifacts to release ########################################
      - name: Add build artifacts to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/osctrl-${{ matrix.components }}-linux-amd64.bin
          asset_name: osctrl-${{ matrix.components }}-${{ github.ref }}-linux-amd64.bin
          asset_content_type: application/x-binary